version: '3.9'

services:
  api:
    build:
      context: ./tarpaulin
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    working_dir: /app
    restart: always

  redis:
    build:
      context: ./redis
    ports:
      - "6379:6379"
    restart: always

  mongo:
    build:
      context: ./mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    restart: always

volumes:
  mongodb_data:
